config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  namespace :admin do
    resources :managements, only: [:index, :show, :edit, :update, :destroy]
  end
  get "search", to: 'articles#search'
  devise_for :users do
    get:favorite_articles, on: :collection
  end

  resources :users, only: [:show]

  resources :articles do
    resources :comments, only: [:create]
    resources :favorite_articles, only: [:create, :destroy]
  end

  resources :tags, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments,          dependent: :destroy
  has_many :article_tags,      dependent: :destroy
  has_many :tags,              through: :article_tags
  has_many :favorite_articles, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  private

  def Article.search(search)
    Article.where(['title LIKE ? OR text LIKE ?', "%#{search}%", "%#{search}%"])
  end

  def Article.category_search(category_id)
    Article.where(category_id: category_id).includes(:user)
  end

  def Article.sort_by_newest
    Article.all.order(Arel.sql('created_at DESC')).includes(:user)
  end

  def Article.sort_by_favorites
    Article.joins(:favorite_articles).group(:article_id).order(Arel.sql('count(favorite_articles.user_id)desc')).includes(:user)
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/articles_tag.rb
class ArticlesTag

  include ActiveModel::Model
  attr_accessor :title, :text, :image, :name, :category_id, :user_id

  with_options presence: true do
    validates :title
    validates :text
    validates :image
    validates :category_id, numericality: { other_than: 1 }
    validates :name
  end

  def save
    article = Article.create(title: title, text: text, image: image, category_id: category_id, user_id: user_id)
    tag = Tag.find_or_create_by(name: name)

    ArticleTag.create(article_id: article.id, tag_id: tag.id)
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Music' },
    { id: 3, name: 'MAG' },
    { id: 4, name: 'Sports' },
    { id: 5, name: 'IT'},
    { id: 6, name: 'Science' },
    { id: 7, name: 'Other' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :text, presence: true
end

app/models/favorite_article.rb
class FavoriteArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates_uniqueness_of :article_id, scope: :user_id 
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_articles, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true, uniqueness: {case_sensitive: true}

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource.id)
  end

  def article_find
    @article = Article.find(params[:id])
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :article_find, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category_id].present?
      @articles = Article.category_search(params[:category_id])
    elsif params[:option] == "B"
      @articles = Article.sort_by_newest
    elsif params[:option] == "A"
      @articles = Article.sort_by_favorites
    else
      @articles = Article.all.includes(:user)
    end
    @tags = Tag.joins(:article_tags).group(:tag_id).order(Arel.sql('count(article_id)desc')).includes(:articles)
  end

  def show
    @comments = @article.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @article = ArticlesTag.new
  end

  def create
    @article = ArticlesTag.new(article_params)
    if @article.valid?
      @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    if current_user.id != @article.user_id
      redirect_to root_path
    end
  end

  def update
    if @article.update(update_article_params)
      redirect_to article_path(@article.id)
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @articles = Article.search(params[:search])
    render 'index'
  end

  private

  def article_params
    params.permit(:title, :text, :image, :name, :category_id).merge(user_id: current_user.id)
  end

  def update_article_params
    params.require(:article).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to article_path(@comment.article_id)
    else
      @article = @comment.article
      @comments = @article.comments
      render 'articles/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, article_id: params[:article_id])
  end
end

app/controllers/favorite_articles_controller.rb
class FavoriteArticlesController < ApplicationController
  before_action :set_article
  before_action :authenticate_user!

  def create
    if @article.user_id != current_user.id
      @favorite_article = FavoriteArticle.create(user_id: current_user.id, article_id: @article.id)
      redirect_to article_path(@article.id)
    end
  end

  def destroy
    @favorite_article = FavoriteArticle.find_by(user_id: current_user.id, article_id: @article.id)
    @favorite_article.destroy
    redirect_to article_path(@article.id)
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to root_path
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to :back
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to root_path
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to :back
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.order(:name)
  end

  def show
    @tag = Tag.find(params[:id])
    @articles = @tag.articles.all.includes(:user)
    @tags = Tag.joins(:article_tags).group(:tag_id).order(Arel.sql('count(article_id)desc')).includes(:articles)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_articles_helper.rb
module FavoriteArticlesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<%= render 'layouts/header' %>

<%= render partial: 'layouts/edit_form' %>

app/views/articles/index.html.erb
<%= render 'layouts/header' %>

<main class="main-contents">

  <div class="main-top">
    <% unless user_signed_in? %>
      <div class="introduction">
        <div class='introduction-top'>
          <h1 class="introduction-top-t">世界を見てみよう</h1>
          <i class="fas fa-globe-asia"></i>
        </div>
        <div class='introduction-bottom'>
          <div class='introduction-bottom-l'>
            <div class='introduction-share'>
              <span class="introduction-share-t">Share</span>
              <i class="fas fa-share-alt"></i>
            </div>
            <div class='introduction-comment'>
              <span class="introduction-comment-t">Comment</span>
              <i class="far fa-comment-alt"></i>
            </div>
            <div class='introduction-favorite'>
              <span class="introduction-favorite-t">Favorite</span>
              <i class="far fa-star"></i>
            </div>
          </div>
          <div class='introduction-bottom-r'>
            <%= link_to new_user_registration_path, class: 'introduction-signup' do%>
              <span>
              Go<br>
              Sign Up
              </span>
              <i class="fas fa-user-plus"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="main-middle">

    <div class="main-center">
      <div class="contents-tags">
        <h2><%= link_to 'Trend', articles_path(option: "A"), class: "tag" %></h2>
        <h2><%= link_to 'New', articles_path(option: "B"), class: "tag" %></h2>
        <h2><%= link_to 'Music', articles_path(category_id: 2), class: "tag" %></h2>
        <h2><%= link_to 'MAG', articles_path(category_id: 3), class: "tag" %></h2>
        <h2><%= link_to 'Sports', articles_path(category_id: 4), class: "tag" %></h2>
        <h2><%= link_to 'IT', articles_path(category_id: 5), class: "tag" %></h2>
        <h2><%= link_to 'Science', articles_path(category_id: 6), class: "tag" %></h2>
        <h2><%= link_to 'Other', articles_path(category_id: 7), class: "tag" %></h2>
      </div>
      
      <%= render 'layouts/articles'%>

    </div>

    <div class="main-right">
      <%= render 'layouts/tags'%>
    </div>
  </div>
</main>

app/views/articles/new.html.erb
<%= render 'layouts/header'%>

<div class="main-contents">
  <%= render partial: 'layouts/new_form' %>
</div>

app/views/articles/show.html.erb
<%= render 'layouts/header' %>

<div class='article'>

  <h1 class='article-title'>
    <%= @article.title %>
    <% if user_signed_in? %>
      <% if !FavoriteArticle.exists?(user_id: current_user.id, article_id: @article.id) %>
        <%= link_to article_favorite_articles_path(@article.id), method: :post do %>
          <i class="fas fa-star"></i>
        <% end %>
      <% else %>
        <%= link_to article_favorite_article_path(@article.id), method: :delete do %>
          <i class="fas fa-star yellow"></i>
        <% end %>
      <% end %>
    <% end %>
  </h1>

  <div class='article-edit-delete'>
    <% if user_signed_in? %>
      <% if current_user.id == @article.user_id || current_user.admin == true %>
        <%= link_to '編集', edit_article_path(@article.id), class: 'article-menu' %>
        <%= link_to '削除', article_path(@article.id), method: :delete, class: 'article-menu' %>
      <% end %>
    <% end %>
  </div>

  <div class='article-info'>

    <div class='article-user-contents'>
      <h2><%= link_to @article.user.nickname, user_path(@article.user.id), class: 'article-user-nickname' %></h2>
      <%= render 'relationships/follow_button', user: @article.user %>
    </div>

    <h2><%=link_to @article.category.name, articles_path(category_id: @article.category.id), class: "article-category" %></h2>
    <%@article.tags.each do |tag| %>
      <h2><%= link_to "##{tag.name}", tag_path(tag.id), class: "article-tag" %></h2>
    <%end%>
  </div>

  <div class='article-img-contents'>
    <%= image_tag @article.image, class: 'article-img' %>
  </div>

  <div class='article-contents'>
    <h3 class='article-text'>
      <%= @article.text %>
    </h3>
  </div>

  <div class="comments">
    <h2>All Comments</h1>
    <% if @comments.present?%>
      <ul class=comments-lists>
        <% @comments.each do |comment|%>
          <li class="comment-content">
            <div class="comment-text"><%= comment.text %></div>
            <div class="comment-right">
              <%= link_to comment.user.nickname, user_path(comment.user.id), class: "comment-user" %>
              <div class="comment-created-at"><%= comment.created_at.strftime("%Y-%m-%d %H:%M")%></div>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>

    <div class="comment-form">
      <% if user_signed_in? %>
        <%= form_with model: @comment, url: article_comments_path(@article.id), local: true do |f| %>
          <%= f.text_field :text %>
          <%= f.submit "Comment"%>
        <% end %>
      <% end%>
    </div>

  </div>
</div> 

app/views/tags/index.html.erb
<%= render 'layouts/header'%>

<main class="main-contents">

  <div class="main-middle">

    <div class="main-center">
      <div class="main-center-top-t">
        <h2 class="all-tag-name">All Tags</h2>
      </div>
      
      <%if @tags.present?%>
        <div class="tags-list">
          <% @tags.each do |tag|%>
            <h2><%= link_to tag.name, tag_path(tag.id), class: "tag-name"%></h2>
          <%end%>
        </div>
      <%else%>
        <h3>初めての共有者になろう→<%= link_to '投稿する', article_path, class: "new-post"%>
      <%end%>
    </div>
  </div>
</main>

app/views/tags/show.html.erb
<%= render 'layouts/header'%>

<main class="main-contents">

  <div class="main-middle">

    <div class="main-center">
      <div class="main-center-top">
        <h2 class="tag-name"><%=@tag.name%></h2>
      </div>
      
      <%= render 'layouts/articles'%>

    </div>

    <div class="main-right">
      <%= render 'layouts/tags'%>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<h1><%= @user.nickname%>'s Page</h1>
<div class='user-info'>

  <div class="nickname">
    <h2>Nick Name</h2>
    <%= @user.nickname %>
  </div>

  <div class='self-introduction'>
    <h2>Introduce</h2>
    <% if @user.self_introduction.blank? %>
      ---
    <% else %>
      <%= @user.self_introduction %>
    <% end %>
  </div>

  <div class="prefecture">
    <h2>Prefecture</h2>
    <% if @user.prefecture_id.blank? %>
      ---
    <% else %>
      <%= @user.prefecture.name %>
    <% end %>
  </div>

  <div class="birthday">
    <h2>Birthday</h2>
    <% if @user.birthday.blank? %>
      ---
    <% else %>
      <%= @user.birthday %>
    <% end %>
  </div>


</div>