config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  namespace :admin do
    resources :managements, only: [:index, :show, :edit, :update, :destroy]
  end
  get "search", to: 'articles#search'
  devise_for :users do
    get:favorite_articles, on: :collection
  end

  resources :users, only: [:show]

  resources :articles do
    resources :comments, only: [:create]
    resources :favorite_articles, only: [:create, :destroy]
  end

  resources :tags, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments,          dependent: :destroy
  has_many :article_tags,      dependent: :destroy
  has_many :tags,              through: :article_tags
  has_many :favorite_articles, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  private

  def Article.search(search)
    Article.where(['title LIKE ? OR text LIKE ?', "%#{search}%", "%#{search}%"])
  end

  def Article.category_search(category_id)
    Article.where(category_id: category_id).includes(:user)
  end

  def Article.sort_by_newest
    Article.all.order(Arel.sql('created_at DESC')).includes(:user)
  end

  def Article.sort_by_favorites
    Article.joins(:favorite_articles).group(:article_id).order(Arel.sql('count(favorite_articles.user_id)desc')).includes(:user)
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/articles_tag.rb
class ArticlesTag

  include ActiveModel::Model
  attr_accessor :title, :text, :image, :name, :category_id, :user_id

  with_options presence: true do
    validates :title
    validates :text
    validates :image
    validates :category_id, numericality: { other_than: 1 }
    validates :name
  end

  def save
    article = Article.create(title: title, text: text, image: image, category_id: category_id, user_id: user_id)
    tag = Tag.find_or_create_by(name: name)

    ArticleTag.create(article_id: article.id, tag_id: tag.id)
  end
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Music' },
    { id: 3, name: 'MAG' },
    { id: 4, name: 'Sports' },
    { id: 5, name: 'IT'},
    { id: 6, name: 'Science' },
    { id: 7, name: 'Other' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates :text, presence: true
end

app/models/favorite_article.rb
class FavoriteArticle < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates_uniqueness_of :article_id, scope: :user_id 
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorite_articles, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :nickname, presence: true, uniqueness: {case_sensitive: true}

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :article_find, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category_id].present?
      @articles = Article.category_search(params[:category_id])
    elsif params[:option] == "B"
      @articles = Article.sort_by_newest
    elsif params[:option] == "A"
      @articles = Article.sort_by_favorites
    else
      @articles = Article.all.includes(:user)
    end
    @tags = Tag.joins(:article_tags).group(:tag_id).order(Arel.sql('count(article_id)desc')).includes(:articles)
  end

  def show
    @comments = @article.comments.includes(:user)
    @comment = Comment.new
  end

  def new
    @article = ArticlesTag.new
  end

  def create
    @article = ArticlesTag.new(article_params)
    if @article.valid?
      @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    if current_user.id != @article.user_id
      redirect_to root_path
    end
  end

  def update
    if @article.update(update_article_params)
      redirect_to article_path(@article.id)
    else
      render :edit
    end
  end

  def destroy
    if @article.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def search
    @articles = Article.search(params[:search])
    render 'index'
  end

  private

  def article_params
    params.permit(:title, :text, :image, :name, :category_id).merge(user_id: current_user.id)
  end

  def update_article_params
    params.require(:article).permit(:title, :text, :image).merge(user_id: current_user.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to article_path(@comment.article_id)
    else
      @article = @comment.article
      @comments = @article.comments
      render 'articles/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, article_id: params[:article_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.order(:name)
  end

  def show
    @tag = Tag.find(params[:id])
    @articles = @tag.articles.all.includes(:user)
    @tags = Tag.joins(:article_tags).group(:tag_id).order(Arel.sql('count(article_id)desc')).includes(:articles)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorite_articles_helper.rb
module FavoriteArticlesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_articles.html.erb
<% if @articles.present?%>
  <div class="article-lists">
    <% @articles.each do |article| %>
      <div class="article-list">
        <div class="article-top">
          <%= link_to article_path(article.id) do %>
            <%= image_tag article.image, class: 'article-img' %>
          <%end%>
        </div>
        <div class="article-bottom">
          <h2 class="article-title1"><%= link_to article.title, article_path(article.id), class: 'article-title' %></h2>
          <%= link_to article.text, article_path(article.id), class: "article-text" %>
          <div class="article-day-user">
            <%= link_to article.user.nickname, user_path(article.user.id), class: 'article-user' %>
            <%= article.updated_at.strftime("%Y-%m-%d %H:%M") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% else %>
  <div class="article-lists">
    <div class='article-list'>
        <div class='article-left'>
          <%= image_tag 'spicewolf.jpg', class: "article-img" %>
        </div>

        <div class='article-right'>
          <%= link_to "ポートフォリオサイト", '#', class: "article-title" %>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_edit_form.html.erb
<%= form_with model: @article, local: true do |f| %>

  <div class="img-field">
    <%= f.file_field :image, placeholder: "記事画像"%>
  </div>

  <div class="form-field" >
    <%= f.label :title, "記事タイトル" %>
    <%= f.text_field :title, class: "field", autofocus: true %>
  </div>

  <div class="form-field">
    <%= f.label :category_id, "カテゴリー" %>
    <%= @article.category.name%>

  <div class="form-field">
    <%= f.label :name, "タグ" %>
      <%@article.tags.each do |tag| %>
        <%= tag.name %>
      <%end%>
  </div>

  <div class="form-field">
    <%= f.label :text, "本文" %>
    <%= f.text_field :text, class: "field" %>
  </div>

  <div class="actions">
    <%= f.submit "編集する", class: "submit-field" %>

  </div>

<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_form.html.erb
<%= form_with url: articles_path, local: true do |f| %>

  <div class="img-field">
    <%= f.file_field :image, placeholder: "記事画像"%>
  </div>

  <div class="form-field" >
    <%= f.label :title, "記事タイトル" %>
    <%= f.text_field :title, calss: "field", autofocus: true %>
  </div>

  <div class="form-field">
    <%= f.label :category_id, "カテゴリー" %>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, { class: "select-box" })%>

  <div class="form-field">
    <%= f.label :name, "タグ" %>
    <%= f.text_field :name, class: "field" %>
  </div>

  <div class="form-field">
    <%= f.label :text, "本文" %>
    <%= f.text_field :text, class: "field" %>
  </div>

  <div class="actions">
    <%= f.submit "投稿する", class: "submit-field" %>

  </div>

<% end %>

app/views/layouts/_header.html.erb
<header class="header">

  <div class="header-left">

    <%= link_to image_tag('logo.png', class: 'logo-icon'), '/' %>
    
  </div>

  <div class="header-center">

    <div class="contents">
      <%= link_to articles_path(option: "A"), class: "content-link" do %>
        <i class="fas fa-poll"></i>
        <h2 class="content-name none">Trend</h2>
      <% end %>
      <%= link_to articles_path(option: "B"), class: "content-link" do %>
        <i class="far fa-clock"></i>
        <h2 class="content-name none">New</h2>
      <% end %>

      <div class="search">
        <%= form_with url: search_path, method: :get, class: 'search-form none1 ', local: true do |f| %>
          <%= f.text_field :search, class: 'search-box' %>
          <%= f.button type: 'submit', class: 'submit' do%>
            <i class="fas fa-search"></i>
          <% end %>
        <% end %>

        <%#div class="day-search none none1">
          <%= link_to "#", class: "content-link" do %>
            <%#i class="far fa-clock"></i>
            <%#h2 class="content-name none">Day Search</h2>
          <%# end %>
        <%#/div>
      <%#/div>%>

      <div class="post">
        <%= link_to new_article_path, class: "content-link" do %>
          <i class="far fa-comment-alt"></i>
          <h2 class="content-name">New Share</h2>
        <% end %>
      </div>

    </div>
    
  </div>

  <div class="header-right">

    <ul class="user-options">
      <% if user_signed_in? %>

        <%#div onclick="obj=document.getElementById('open').style; obj.display=(obj.display=='none')?'block':'none';">
          <a style="cursor:pointer;" class="user-nickname"><%= current_user.nickname %></a>
        <%#/div>

        <%#div id="open" style="display:none;clear:both;">

          <li><%= link_to 'MY PAGE', user_path(current_user.id), class: "user-nickname"%></li>

          <%#<li><%= link_to 'OPTIONS', "#", class: "user-nickname"  %></li>

          <%# if current_user.admin == true %>
            <%#<li><%= link_to 'ADMIN PAGE', admin_managements_path, class: "logout" %></li>
          <%# end %>

          <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class: "logout"  %></li>
        <%#/div%>
        
      <% else %>
        <li><%= link_to 'LOGIN', new_user_session_path, method: :get, class: "login" %></li>
        <li><%= link_to 'SIGN UP', new_user_registration_path, method: :get, class: "sign-up" %></li>
      <% end %>
    </ul>
    
  </div>

</header>

app/views/layouts/_new_form.html.erb
<div class="main-form">
  <%= form_with url: articles_path, class: "article-form", local: true do |f| %>

    <div class="title-field" >
      <%= f.text_field :title, placeholder: "Title", class: "title-form", autofocus: true %>
    </div>

    <div class="info-field">

      <div class="img-field">
        <%= f.label :image, "IMAGE"%>
        <%= f.file_field :image, placeholder: "記事画像"%>
      </div>

      <div class="category-field">
        <%= f.label :category_id, "Category" %>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, { class: "select-box" })%>
      </div>

      <div class="tag-field">
        <%= f.label :name, "Tag" %>
        <%= f.text_field :name, class: "field" %>
      </div>
    </div>

    <div class="text-field">
      <%= f.text_area :text, placeholder: "Text", class: "text-form" %>
    </div>

    <div class="actions">
      <%= f.submit "Share", class: "submit-field" %>
    </div>

  <% end %>
</div>

app/views/layouts/_tags.html.erb
<% if @tags.present? %>
  <h2 class='alltags-links'><%= link_to  'All Tags', tags_path, class: "alltags-link"%></h2>
  <div class="tag-lists">
    <% @tags.each do |tag| %>
      <%= link_to "#{tag.name}(#{tag.articles.length})", tag_path(id: tag.id), class: "tag-link" %>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>